<?php

declare(strict_types=1);

namespace tommyknocker\pdodb\tests\oracle;

use tommyknocker\pdodb\helpers\Db;

/**
 * HelpersTests tests for Oracle.
 */
final class HelpersTests extends BaseOracleTestCase
{
    public function testLikeAndIlikeHelpers(): void
    {
        $db = self::$db;

        $db->find()->table('users')->insert(['name' => 'Alice', 'company' => 'WonderCorp', 'age' => 30]);
        $db->find()->table('users')->insert(['name' => 'Bob', 'company' => 'wondercorp', 'age' => 35]);

        // LIKE
        $likeResults = $db->find()
            ->from('users')
            ->where(Db::like('company', 'Wonder%'))
            ->get();

        $this->assertCount(1, $likeResults); // Oracle LIKE is case-sensitive
        $this->assertEquals('Alice', $likeResults[0]['NAME']);

        // ILIKE (case-insensitive LIKE)
        $ilikeResults = $db->find()
            ->from('users')
            ->where(Db::ilike('company', 'Wonder%'))
            ->get();

        $this->assertCount(2, $ilikeResults);
    }

    public function testInAndNotInHelpers(): void
    {
        $db = self::$db;

        $db->find()->table('users')->insert(['name' => 'Dana', 'company' => 'X', 'age' => 40]);
        $db->find()->table('users')->insert(['name' => 'Eve', 'company' => 'Y', 'age' => 45]);
        $db->find()->table('users')->insert(['name' => 'Frank', 'company' => 'Z', 'age' => 50]);

        $inResults = $db->find()
            ->from('users')
            ->where(Db::in('name', ['Dana', 'Eve']))
            ->get();

        $this->assertCount(2, $inResults);

        $notInResults = $db->find()
            ->from('users')
            ->where(Db::not(Db::in('name', ['Dana', 'Eve'])))
            ->get();

        $this->assertCount(1, $notInResults);
        $this->assertEquals('Frank', $notInResults[0]['NAME']);
    }

    public function testToTsHelper(): void
    {
        $db = self::$db;

        // Create table with TIMESTAMP column
        $db->rawQuery('BEGIN EXECUTE IMMEDIATE \'DROP TABLE t_oracle_helpers\'; EXCEPTION WHEN OTHERS THEN NULL; END;');
        $db->rawQuery('CREATE TABLE t_oracle_helpers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_time TIMESTAMP,
            event_date DATE
        )');

        // Test TO_TIMESTAMP with default format in INSERT
        $id1 = $db->find()->table('t_oracle_helpers')->insert([
            'event_time' => Db::toTs('2025-10-20 09:00:00'),
        ]);
        $this->assertIsInt($id1);

        $row = $db->find()
            ->from('t_oracle_helpers')
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['EVENT_TIME']);

        // Test TO_TIMESTAMP with custom format in INSERT
        $id2 = $db->find()->table('t_oracle_helpers')->insert([
            'event_time' => Db::toTs('20-10-2025 09:00:00', 'DD-MM-YYYY HH24:MI:SS'),
        ]);
        $this->assertIsInt($id2);

        $row = $db->find()
            ->from('t_oracle_helpers')
            ->where('id', $id2)
            ->getOne();
        $this->assertNotNull($row['EVENT_TIME']);

        // Test TO_TIMESTAMP in SELECT
        $row = $db->find()
            ->from('t_oracle_helpers')
            ->select(['converted_time' => Db::toTs('2025-10-20 14:30:00')])
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['CONVERTED_TIME']);
    }

    public function testToDateHelper(): void
    {
        $db = self::$db;

        // Create table with DATE column
        $db->rawQuery('BEGIN EXECUTE IMMEDIATE \'DROP TABLE t_oracle_helpers\'; EXCEPTION WHEN OTHERS THEN NULL; END;');
        $db->rawQuery('CREATE TABLE t_oracle_helpers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_date DATE
        )');

        // Test TO_DATE with default format in INSERT
        $id1 = $db->find()->table('t_oracle_helpers')->insert([
            'event_date' => Db::toDate('2025-10-20'),
        ]);
        $this->assertIsInt($id1);

        $row = $db->find()
            ->from('t_oracle_helpers')
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['EVENT_DATE']);

        // Test TO_DATE with custom format in INSERT
        $id2 = $db->find()->table('t_oracle_helpers')->insert([
            'event_date' => Db::toDate('20-10-2025', 'DD-MM-YYYY'),
        ]);
        $this->assertIsInt($id2);

        $row = $db->find()
            ->from('t_oracle_helpers')
            ->where('id', $id2)
            ->getOne();
        $this->assertNotNull($row['EVENT_DATE']);

        // Test TO_DATE in SELECT
        $row = $db->find()
            ->from('t_oracle_helpers')
            ->select(['converted_date' => Db::toDate('2025-10-21')])
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['CONVERTED_DATE']);
    }

    public function testToCharHelper(): void
    {
        $db = self::$db;

        // Create table with CLOB column
        $db->rawQuery('BEGIN EXECUTE IMMEDIATE \'DROP TABLE t_oracle_helpers\'; EXCEPTION WHEN OTHERS THEN NULL; END;');
        $db->rawQuery('CREATE TABLE t_oracle_helpers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            text_value CLOB,
            numeric_value NUMBER
        )');

        // Insert test data
        $id1 = $db->find()->table('t_oracle_helpers')->insert([
            'text_value' => 'Test CLOB value',
            'numeric_value' => 12345,
        ]);
        $this->assertIsInt($id1);

        // Test TO_CHAR with CLOB column
        $row = $db->find()
            ->from('t_oracle_helpers')
            ->select(['char_value' => Db::toChar('text_value')])
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['CHAR_VALUE']);
        $this->assertEquals('Test CLOB value', $row['CHAR_VALUE']);

        // Test TO_CHAR with numeric column
        $row = $db->find()
            ->from('t_oracle_helpers')
            ->select(['char_numeric' => Db::toChar('numeric_value')])
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['CHAR_NUMERIC']);
        $this->assertEquals('12345', $row['CHAR_NUMERIC']);

        // Test TO_CHAR with RawValue
        $row = $db->find()
            ->from('t_oracle_helpers')
            ->select(['char_raw' => Db::toChar(Db::raw('numeric_value + 100'))])
            ->where('id', $id1)
            ->getOne();
        $this->assertNotNull($row['CHAR_RAW']);
        $this->assertEquals('12445', $row['CHAR_RAW']);
    }
}
