<?php

declare(strict_types=1);

namespace tommyknocker\pdodb\cli;

use tommyknocker\pdodb\PdoDb;

/**
 * Service generator for service classes.
 *
 * Generates service classes with business logic methods.
 */
class ServiceGenerator extends BaseCliCommand
{
    /**
     * Generate a service from a repository.
     *
     * @param string $serviceName Service class name
     * @param string|null $repositoryName Repository class name (optional)
     * @param string|null $outputPath Output path for service file (optional)
     * @param PdoDb|null $db Database instance (optional)
     * @param string|null $namespace Service namespace (optional)
     * @param string|null $repositoryNamespace Repository namespace (optional)
     * @param bool $force Overwrite existing file
     *
     * @return string Path to created service file
     */
    public static function generate(
        string $serviceName,
        ?string $repositoryName = null,
        ?string $outputPath = null,
        ?PdoDb $db = null,
        ?string $namespace = null,
        ?string $repositoryNamespace = null,
        bool $force = false
    ): string {
        if ($db === null) {
            $db = static::createDatabase();
        }
        $driver = static::getDriverName($db);

        if (getenv('PHPUNIT') === false) {
            echo "PDOdb Service Generator\n";
            echo "Database: {$driver}\n\n";
        }

        // Validate service name
        if (!preg_match('/^[A-Z][a-zA-Z0-9]*$/', $serviceName)) {
            static::error("Invalid service name: {$serviceName}. Service name must start with uppercase letter and contain only alphanumeric characters.");
        }

        // Get repository name
        if ($repositoryName === null) {
            // Auto-detect from service name (remove "Service" suffix, add "Repository")
            $repositoryName = static::serviceNameToRepositoryName($serviceName);
            $repositoryName = static::readInput('Enter repository class name', $repositoryName);
        }

        // Get output path
        if ($outputPath === null) {
            $outputPath = static::getServiceOutputPath();
        }

        // Generate service code
        $serviceNamespace = $namespace !== null && $namespace !== '' ? $namespace : 'App\\Services';
        $repositoryNamespaceFinal = $repositoryNamespace !== null && $repositoryNamespace !== '' ? $repositoryNamespace : 'App\\Repositories';
        $serviceCode = static::generateServiceCode(
            $serviceName,
            $repositoryName,
            $serviceNamespace,
            $repositoryNamespaceFinal
        );

        // Write service file
        $filename = $outputPath . '/' . $serviceName . '.php';
        if (file_exists($filename)) {
            $overwrite = $force ? true : static::readConfirmation('Service file already exists. Overwrite?', false);
            if (!$overwrite) {
                static::info('Service generation cancelled.');
                exit(0);
            }
        }

        file_put_contents($filename, $serviceCode);

        static::success('Service file created: ' . basename($filename));
        if (getenv('PHPUNIT') === false) {
            echo "  Path: {$filename}\n";
            echo "  Repository: {$repositoryNamespaceFinal}\\{$repositoryName}\n";
        }

        return $filename;
    }

    /**
     * Convert service name to repository name.
     *
     * @param string $serviceName Service name (e.g. "UserService")
     *
     * @return string Repository name (e.g. "UserRepository")
     */
    protected static function serviceNameToRepositoryName(string $serviceName): string
    {
        // Remove "Service" suffix if present, add "Repository"
        if (str_ends_with($serviceName, 'Service')) {
            return substr($serviceName, 0, -7) . 'Repository';
        }
        return $serviceName . 'Repository';
    }

    /**
     * Generate service code.
     *
     * @param string $serviceName Service class name
     * @param string $repositoryName Repository class name
     * @param string $serviceNamespace Service namespace
     * @param string $repositoryNamespace Repository namespace
     *
     * @return string
     */
    protected static function generateServiceCode(
        string $serviceName,
        string $repositoryName,
        string $serviceNamespace,
        string $repositoryNamespace
    ): string {
        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$serviceNamespace};

use tommyknocker\pdodb\PdoDb;
use {$repositoryNamespace}\\{$repositoryName};

/**
 * Service class for {$repositoryName}.
 *
 * Auto-generated by PDOdb Service Generator
 */
class {$serviceName}
{
    protected PdoDb \$db;
    protected {$repositoryName} \$repository;

    /**
     * Create service instance.
     *
     * @param PdoDb \$db Database instance
     * @param {$repositoryName} \$repository Repository instance
     */
    public function __construct(PdoDb \$db, {$repositoryName} \$repository)
    {
        \$this->db = \$db;
        \$this->repository = \$repository;
    }

    /**
     * Get repository instance.
     *
     * @return {$repositoryName}
     */
    protected function getRepository(): {$repositoryName}
    {
        return \$this->repository;
    }

    // TODO: Add your business logic methods here
    // Example:
    //
    // /**
    //  * Create user with profile.
    //  *
    //  * @param array<string, mixed> \$userData User data
    //  * @param array<string, mixed> \$profileData Profile data
    //  *
    //  * @return int User ID
    //  */
    // public function createUserWithProfile(array \$userData, array \$profileData): int
    // {
    //     \$this->db->startTransaction();
    //
    //     try {
    //         \$userId = \$this->repository->create(\$userData);
    //         \$profileData['user_id'] = \$userId;
    //         \$this->db->find()->table('profiles')->insert(\$profileData);
    //
    //         \$this->db->commit();
    //         return \$userId;
    //     } catch (\Exception \$e) {
    //         \$this->db->rollback();
    //         throw \$e;
    //     }
    // }
}

PHP;

        return $code;
    }

    /**
     * Get service output path.
     *
     * @return string
     */
    protected static function getServiceOutputPath(): string
    {
        // Check environment variable first
        $path = getenv('PDODB_SERVICE_PATH');
        if ($path && is_dir($path)) {
            return $path;
        }

        // Check common locations
        $possiblePaths = [
            getcwd() . '/app/Services',
            getcwd() . '/src/Services',
            getcwd() . '/services',
            __DIR__ . '/../../services',
        ];

        foreach ($possiblePaths as $path) {
            if (is_dir($path)) {
                return $path;
            }
        }

        // Create default services directory
        $defaultPath = getcwd() . '/services';
        if (!is_dir($defaultPath)) {
            mkdir($defaultPath, 0755, true);
        }

        return $defaultPath;
    }
}
